
"""Country name / ISO code → currency metadata."""

# Canonical: country name (as returned by ip-api) → (currency_code, symbol, flag)
COUNTRY_CURRENCY = {
    # Europe — EUR zone + others
    "Germany": ("EUR", "€", "🇩🇪"),
    "France": ("EUR", "€", "🇫🇷"),
    "Italy": ("EUR", "€", "🇮🇹"),
    "Spain": ("EUR", "€", "🇪🇸"),
    "Netherlands": ("EUR", "€", "🇳🇱"),
    "Belgium": ("EUR", "€", "🇧🇪"),
    "Austria": ("EUR", "€", "🇦🇹"),
    "Portugal": ("EUR", "€", "🇵🇹"),
    "Ireland": ("EUR", "€", "🇮🇪"),
    "Finland": ("EUR", "€", "🇫🇮"),
    "Greece": ("EUR", "€", "🇬🇷"),
    "Slovakia": ("EUR", "€", "🇸🇰"),
    "Slovenia": ("EUR", "€", "🇸🇮"),
    "Luxembourg": ("EUR", "€", "🇱🇺"),
    "Estonia": ("EUR", "€", "🇪🇪"),
    "Latvia": ("EUR", "€", "🇱🇻"),
    "Lithuania": ("EUR", "€", "🇱🇹"),
    "Malta": ("EUR", "€", "🇲🇹"),
    "Cyprus": ("EUR", "€", "🇨🇾"),
    "Croatia": ("EUR", "€", "🇭🇷"),
    "United Kingdom": ("GBP", "£", "🇬🇧"),
    "Switzerland": ("CHF", "CHF", "🇨🇭"),
    "Sweden": ("SEK", "kr", "🇸🇪"),
    "Norway": ("NOK", "kr", "🇳🇴"),
    "Denmark": ("DKK", "kr", "🇩🇰"),
    "Poland": ("PLN", "zł", "🇵🇱"),
    "Czech Republic": ("CZK", "Kč", "🇨🇿"),
    "Czechia": ("CZK", "Kč", "🇨🇿"),
    "Hungary": ("HUF", "Ft", "🇭🇺"),
    "Romania": ("RON", "lei", "🇷🇴"),
    "Bulgaria": ("BGN", "лв", "🇧🇬"),
    "Ukraine": ("UAH", "₴", "🇺🇦"),
    "Russia": ("RUB", "₽", "🇷🇺"),
    "Turkey": ("TRY", "₺", "🇹🇷"),
    # Americas — user rule: USA + Canada → USD
    "United States": ("USD", "$", "🇺🇸"),
    "Canada": ("USD", "$", "🇨🇦"),
    "Mexico": ("MXN", "MX$", "🇲🇽"),
    "Brazil": ("BRL", "R$", "🇧🇷"),
    "Argentina": ("ARS", "$", "🇦🇷"),
    "Chile": ("CLP", "$", "🇨🇱"),
    "Colombia": ("COP", "$", "🇨🇴"),
    "Peru": ("PEN", "S/", "🇵🇪"),
    # Africa
    "Uganda": ("UGX", "UGX", "🇺🇬"),
    "Kenya": ("KES", "KSh", "🇰🇪"),
    "Tanzania": ("TZS", "TSh", "🇹🇿"),
    "Rwanda": ("RWF", "FRw", "🇷🇼"),
    "Burundi": ("BIF", "FBu", "🇧🇮"),
    "South Sudan": ("SSP", "£", "🇸🇸"),
    "Sudan": ("SDG", "£", "🇸🇩"),
    "Ethiopia": ("ETB", "Br", "🇪🇹"),
    "Somalia": ("SOS", "Sh", "🇸🇴"),
    "Djibouti": ("DJF", "Fdj", "🇩🇯"),
    "Eritrea": ("ERN", "Nfk", "🇪🇷"),
    "Nigeria": ("NGN", "₦", "🇳🇬"),
    "Ghana": ("GHS", "GH₵", "🇬🇭"),
    "South Africa": ("ZAR", "R", "🇿🇦"),
    "Egypt": ("EGP", "E£", "🇪🇬"),
    "Morocco": ("MAD", "DH", "🇲🇦"),
    "Algeria": ("DZD", "DA", "🇩🇿"),
    "Tunisia": ("TND", "DT", "🇹🇳"),
    "Libya": ("LYD", "LD", "🇱🇾"),
    "Cameroon": ("XAF", "FCFA", "🇨🇲"),
    "Senegal": ("XOF", "CFA", "🇸🇳"),
    "Ivory Coast": ("XOF", "CFA", "🇨🇮"),
    "Côte d'Ivoire": ("XOF", "CFA", "🇨🇮"),
    "Mali": ("XOF", "CFA", "🇲🇱"),
    "Burkina Faso": ("XOF", "CFA", "🇧🇫"),
    "Niger": ("XOF", "CFA", "🇳🇪"),
    "Togo": ("XOF", "CFA", "🇹🇬"),
    "Benin": ("XOF", "CFA", "🇧🇯"),
    "Guinea": ("GNF", "FG", "🇬🇳"),
    "Sierra Leone": ("SLE", "Le", "🇸🇱"),
    "Liberia": ("LRD", "L$", "🇱🇷"),
    "Gambia": ("GMD", "D", "🇬🇲"),
    "Zambia": ("ZMW", "ZK", "🇿🇲"),
    "Zimbabwe": ("USD", "$", "🇿🇼"),
    "Botswana": ("BWP", "P", "🇧🇼"),
    "Namibia": ("NAD", "N$", "🇳🇦"),
    "Mozambique": ("MZN", "MT", "🇲🇿"),
    "Malawi": ("MWK", "MK", "🇲🇼"),
    "Angola": ("AOA", "Kz", "🇦🇴"),
    "Congo": ("XAF", "FCFA", "🇨🇬"),
    "Republic of the Congo": ("XAF", "FCFA", "🇨🇬"),
    "Democratic Republic of the Congo": ("CDF", "FC", "🇨🇩"),
    "DR Congo": ("CDF", "FC", "🇨🇩"),
    "Gabon": ("XAF", "FCFA", "🇬🇦"),
    "Madagascar": ("MGA", "Ar", "🇲🇬"),
    "Mauritius": ("MUR", "₨", "🇲🇺"),
    "Seychelles": ("SCR", "₨", "🇸🇨"),
    # Asia
    "India": ("INR", "₹", "🇮🇳"),
    "China": ("CNY", "¥", "🇨🇳"),
    "Japan": ("JPY", "¥", "🇯🇵"),
    "South Korea": ("KRW", "₩", "🇰🇷"),
    "Indonesia": ("IDR", "Rp", "🇮🇩"),
    "Malaysia": ("MYR", "RM", "🇲🇾"),
    "Singapore": ("SGD", "S$", "🇸🇬"),
    "Thailand": ("THB", "฿", "🇹🇭"),
    "Vietnam": ("VND", "₫", "🇻🇳"),
    "Philippines": ("PHP", "₱", "🇵🇭"),
    "Pakistan": ("PKR", "₨", "🇵🇰"),
    "Bangladesh": ("BDT", "৳", "🇧🇩"),
    "Sri Lanka": ("LKR", "Rs", "🇱🇰"),
    "Nepal": ("NPR", "Rs", "🇳🇵"),
    "United Arab Emirates": ("AED", "د.إ", "🇦🇪"),
    "Saudi Arabia": ("SAR", "﷼", "🇸🇦"),
    "Qatar": ("QAR", "﷼", "🇶🇦"),
    "Kuwait": ("KWD", "د.ك", "🇰🇼"),
    "Bahrain": ("BHD", "BD", "🇧🇭"),
    "Oman": ("OMR", "﷼", "🇴🇲"),
    "Israel": ("ILS", "₪", "🇮🇱"),
    "Jordan": ("JOD", "JD", "🇯🇴"),
    "Lebanon": ("LBP", "ل.ل", "🇱🇧"),
    "Iraq": ("IQD", "ع.د", "🇮🇶"),
    "Iran": ("IRR", "﷼", "🇮🇷"),
    "Hong Kong": ("HKD", "HK$", "🇭🇰"),
    "Taiwan": ("TWD", "NT$", "🇹🇼"),
    "Mongolia": ("MNT", "₮", "🇲🇳"),
    "Kazakhstan": ("KZT", "₸", "🇰🇿"),
    "Uzbekistan": ("UZS", "so'm", "🇺🇿"),
    # Oceania
    "Australia": ("AUD", "A$", "🇦🇺"),
    "New Zealand": ("NZD", "NZ$", "🇳🇿"),
    "Fiji": ("FJD", "FJ$", "🇫🇯"),
    "Papua New Guinea": ("PGK", "K", "🇵🇬"),
}

# ISO country code → currency (for ip-api countryCode)
ISO_CURRENCY = {
    "DE": ("EUR", "€"), "FR": ("EUR", "€"), "IT": ("EUR", "€"), "ES": ("EUR", "€"),
    "NL": ("EUR", "€"), "BE": ("EUR", "€"), "AT": ("EUR", "€"), "PT": ("EUR", "€"),
    "IE": ("EUR", "€"), "FI": ("EUR", "€"), "GR": ("EUR", "€"), "SK": ("EUR", "€"),
    "SI": ("EUR", "€"), "LU": ("EUR", "€"), "EE": ("EUR", "€"), "LV": ("EUR", "€"),
    "LT": ("EUR", "€"), "MT": ("EUR", "€"), "CY": ("EUR", "€"), "HR": ("EUR", "€"),
    "GB": ("GBP", "£"), "CH": ("CHF", "CHF"), "SE": ("SEK", "kr"), "NO": ("NOK", "kr"),
    "DK": ("DKK", "kr"), "PL": ("PLN", "zł"), "CZ": ("CZK", "Kč"), "HU": ("HUF", "Ft"),
    "RO": ("RON", "lei"), "BG": ("BGN", "лв"), "UA": ("UAH", "₴"), "RU": ("RUB", "₽"),
    "TR": ("TRY", "₺"), "US": ("USD", "$"), "CA": ("USD", "$"), "MX": ("MXN", "MX$"),
    "BR": ("BRL", "R$"), "AR": ("ARS", "$"), "CL": ("CLP", "$"), "CO": ("COP", "$"),
    "PE": ("PEN", "S/"), "UG": ("UGX", "UGX"), "KE": ("KES", "KSh"), "TZ": ("TZS", "TSh"),
    "RW": ("RWF", "FRw"), "BI": ("BIF", "FBu"), "SS": ("SSP", "£"), "SD": ("SDG", "£"),
    "ET": ("ETB", "Br"), "SO": ("SOS", "Sh"), "NG": ("NGN", "₦"), "GH": ("GHS", "GH₵"),
    "ZA": ("ZAR", "R"), "EG": ("EGP", "E£"), "MA": ("MAD", "DH"), "DZ": ("DZD", "DA"),
    "TN": ("TND", "DT"), "CM": ("XAF", "FCFA"), "SN": ("XOF", "CFA"), "CI": ("XOF", "CFA"),
    "IN": ("INR", "₹"), "CN": ("CNY", "¥"), "JP": ("JPY", "¥"), "KR": ("KRW", "₩"),
    "ID": ("IDR", "Rp"), "MY": ("MYR", "RM"), "SG": ("SGD", "S$"), "TH": ("THB", "฿"),
    "VN": ("VND", "₫"), "PH": ("PHP", "₱"), "PK": ("PKR", "₨"), "BD": ("BDT", "৳"),
    "AE": ("AED", "د.إ"), "SA": ("SAR", "﷼"), "QA": ("QAR", "﷼"), "KW": ("KWD", "د.ك"),
    "AU": ("AUD", "A$"), "NZ": ("NZD", "NZ$"), "HK": ("HKD", "HK$"), "TW": ("TWD", "NT$"),
    "IL": ("ILS", "₪"), "ZW": ("USD", "$"), "ZM": ("ZMW", "ZK"), "MW": ("MWK", "MK"),
    "MZ": ("MZN", "MT"), "AO": ("AOA", "Kz"), "CD": ("CDF", "FC"), "CG": ("XAF", "FCFA"),
}


def currency_for_country(country_name=None, country_code=None):
    """Return (code, symbol, flag_or_empty). Defaults to UGX."""
    if country_name and country_name in COUNTRY_CURRENCY:
        return COUNTRY_CURRENCY[country_name]
    if country_code:
        code = country_code.upper().strip()
        if code in ISO_CURRENCY:
            c, s = ISO_CURRENCY[code]
            return (c, s, "")
    return ("UGX", "UGX", "🇺🇬")


def all_country_names():
    return sorted(COUNTRY_CURRENCY.keys())
